// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Author struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Books []*Book `json:"books"`
}

type Book struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Genre       []string  `json:"genre"`
	PublishDate time.Time `json:"publishDate"`
	Author      *Author   `json:"author"`
}
